version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: martinez_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=host.docker.internal
      - DB_DATABASE=martinez
      - DB_USERNAME=root
      - DB_PASSWORD=
      - REDIS_HOST=redis
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - martinez_network

  redis:
    image: redis:7-alpine
    container_name: martinez_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - martinez_network

volumes:
  redis_data:
    driver: local

networks:
  martinez_network:
    driver: bridge
