# Docker Compose completo con MySQL, Redis y phpMyAdmin
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.working
    container_name: martinez_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=martinez
      - DB_USERNAME=martinez_user
      - DB_PASSWORD=martinez_password
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - martinez_network

  mysql:
    image: mysql:8.0
    container_name: martinez_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: martinez
      MYSQL_USER: martinez_user
      MYSQL_PASSWORD: martinez_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - martinez_network

  redis:
    image: redis:7-alpine
    container_name: martinez_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - martinez_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: martinez_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - martinez_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  martinez_network:
    driver: bridge
