[phases.setup]
nixPkgs = ['php82', 'php82Extensions.bcmath', 'php82Extensions.ctype', 'php82Extensions.fileinfo', 'php82Extensions.mbstring', 'php82Extensions.openssl', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.zip', 'php82Packages.composer', 'nodejs-18_x', 'npm-9_x']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npx mix --production'
]

[phases.start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[variables]
PHP_VERSION = "8.2"
NODE_OPTIONS = "--openssl-legacy-provider"
